variables:
  - name: name
    value: aws-bootstrap-terraform
  - name: vmImage
    value: ubuntu-20.04
  - name: awsRegion
    value: eu-west-1
  - name: opsAccountServiceConnection
    value: sje-aws-origin
  - name: targetAccountServiceConnection
    value: sje-aws-labs